version: '3.8'

services:
  devmachine:
    container_name: devmachine
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an version of .NET: 6, 7.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 8.0-bookworm
        # Options
        NODE_VERSION: "lts/*"
    environment:
      SAMPLE_ENV: test
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: service:qdrant
    depends_on:
      - qdrant
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
